"""`/{industry}/stats/generation` — the tick ledger has to be readable (t_ac80c514).

Two independent defects, and the second one is the one that made the data *wrong*
rather than merely unreachable.

1. Unreachable. The route took `last_n_ticks` capped at 1000 with no offset and no
   time window, so the newest-1000 slice was all it could ever serve — measured on the
   dev slot: `last_n_ticks=100` → 100 rows, `=1000` → 1000, `=2000` → HTTP 422, against
   a relation holding ~37k rows. A consumer asking "was the generator running while my
   sales dipped?" could not page to the window it cared about, and a bounded mirror was
   the only design left to it.

2. Incomplete. The ledger has two clocks and a scenario tag, and the *backfill* wrote
   none of it. `run_backfill` — the path that writes every day of a fresh install, and
   every day a gap-fill repairs — never called `record_stats`, so days generated by a
   backfill left no ledger row at all. Measured on dev: `control.generation_stats` starts
   at 2026-09-21 (the first realtime tick) while `pos.transactions` starts 2026-08-22 —
   94,867 transactions across 30 days with zero ledger rows. That is why
   `control.generation_stats` holds 0 rows for 2026-09-05..09-09, the labour-day window:
   not a missing scenario *tag*, but no row to carry one. The holiday regime is stamped
   on the transactions and the orders, so a consumer joining the ledger to explain a dip
   found nothing for exactly the days that need explaining, and read a holiday as an
   unexplained anomaly.

   The gas-station and support backfills both write a stat row per simulated hour
   (`gas-station/generator/main.py`, `support/generator/main.py`); grocery was the odd
   one out, and its own tick loop documents `record_stats()` as a lifecycle phase.

So the guards here are:

* the route is windowed and paged on a PK-terminated order, over **both** clocks — the
  table has `simulation_dt` (business time: the hour the tick simulated) and
  `recorded_at` (insert clock), which is exactly the `start_dt`/`end_dt` +
  `created_after`/`created_before` pairing every other backdated route here uses;
* `last_n_ticks` keeps working (it is the existing UI/readiness consumer's parameter)
  but no longer caps what the route can serve;
* the response is the `{data, total, limit, offset}` envelope every other paginated
  route returns, so `total` can describe a window instead of a bare list;
* the backfill writes a ledger row per simulated hour, stamped with the scenario the
  hour's transactions were generated under — which is the same `ScenarioContext` object
  the hour's rows were written from, so the tag cannot drift from the data.
"""
import pathlib
import re

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
API_SOURCE = REPO_ROOT / "base" / "api" / "main.py"
GENERATOR_MAIN = REPO_ROOT / "grocery" / "generator" / "main.py"

ROUTE_SOURCE_PATH = "/{industry}/stats/generation"
FAR_PAST = "2000-01-01T00:00:00+00:00"
FAR_FUTURE = "2999-01-01T00:00:00+00:00"


def _route_source() -> str:
    """The source of the stats route, from its decorator to the next one."""
    source = API_SOURCE.read_text()
    marker = f'@app.get("{ROUTE_SOURCE_PATH}",'
    start = source.index(marker)
    end = source.index("\n@app.", start + len(marker))
    return source[start:end]


def _backfill_source() -> str:
    """The body of `run_backfill` in the grocery generator."""
    source = GENERATOR_MAIN.read_text()
    start = source.index("def run_backfill")
    return source[start:source.index("\ndef ", start + 10)]


def _backfill_record_stats_call() -> str:
    """The backfill's ledger write — the `record_stats(...)` call.

    Narrower than the hour loop on purpose: the loop already passes `scenario.scenario_tag`
    to `inventory.flush_sales`, so a test that searched the whole loop would report the
    ledger row as tagged when the row itself is untagged.
    """
    backfill = _backfill_source()
    start = backfill.index("record_stats(")
    end = backfill.index(")", backfill.index("sim_dt", start))
    return backfill[start:end + 1]


# ---------------------------------------------------------------------------
# Ask 1 — the route is reachable: paged, windowed, on both clocks
# ---------------------------------------------------------------------------

def test_route_is_paginated_on_a_total_order():
    """A page is only complete if the ORDER BY is a total order.

    `recorded_at` alone is not one: a 30 s tick and the backfill's per-hour rows can
    share a stamp, and a tie cluster straddling a page boundary is returned twice or
    never while `total` still matches — the exact failure class that cost data-lab 272
    `online.order_events` rows (t_d7892e10, t_7c88f2f9).
    """
    body = _route_source()
    assert "OFFSET %s" in body, "the stats route does not paginate"
    order_by = re.findall(r"ORDER BY ([^\n]+)", body)
    assert order_by, "the stats route paginates without an ORDER BY"
    for clause in order_by:
        keys = [part.strip() for part in clause.split(",")]
        last = re.split(r"\s+", keys[-1])[0].split(".")[-1]
        assert last == "stat_id", (
            f"the stats route paginates on {clause!r}; a page must end on the primary "
            "key (stat_id) or tied rows can be double-counted or lost"
        )


def test_route_takes_a_limit_larger_than_the_old_ticks_cap():
    """The old `le=1000` on `last_n_ticks` was the ceiling on the whole relation.

    Both page-size parameters have to be raised above it, since a caller can reach the
    route with either. The annotation is matched loosely (`int` or `Optional[int]`) so
    this pins the *cap*, not the spelling.
    """
    body = _route_source()
    caps = {}
    for name in ("limit", "last_n_ticks"):
        match = re.search(rf"{name}:\s*(?:Optional\[)?int\]?\s*=\s*Query\([^)]*le=(\d+)\)", body)
        assert match, f"the stats route declares no capped {name}"
        caps[name] = int(match.group(1))
    for name, cap in caps.items():
        assert cap > 1000, (
            f"{name} is still capped at {cap}: the relation holds tens of thousands of "
            "rows and a consumer that cannot page is a bounded mirror"
        )


def test_route_window_covers_the_business_clock():
    """`simulation_dt` is business time — when the tick simulated, which a backfill
    backdates. It is what a consumer windows on when asking "what did the generator
    produce for this hour?"."""
    body = _route_source()
    for param in ("start_dt", "end_dt"):
        assert re.search(rf"^\s+{param}: Optional\[datetime\] = None,$", body, re.M), \
            f"the stats route does not declare an optional {param}"
    assert 'filters.append("simulation_dt >= %s"); params.append(start_dt)' in body, \
        "start_dt does not filter simulation_dt"
    assert 'filters.append("simulation_dt <= %s"); params.append(end_dt)' in body, \
        "end_dt does not filter simulation_dt"


def test_route_window_covers_the_insert_clock():
    """`recorded_at` is `DEFAULT NOW()`, written by the same statement as the row, so it
    is monotone and immutable — the only clock a delta load can watermark on.

    This matters here precisely because the backfill backdates: before the backfill
    wrote ledger rows (t_ac80c514) `simulation_dt` was fine for realtime ticks, but a
    backfilled day would sit below the watermark and become unreachable. With both
    windows the two families are read with the clock that suits them.
    """
    body = _route_source()
    for param in ("created_after", "created_before"):
        assert re.search(rf"^\s+{param}: Optional\[datetime\] = None,$", body, re.M), \
            f"the stats route does not declare an optional {param}"
    assert 'filters.append("recorded_at >= %s"); params.append(created_after)' in body, \
        "created_after does not filter recorded_at"
    assert 'filters.append("recorded_at <= %s"); params.append(created_before)' in body, \
        "created_before does not filter recorded_at"


def test_route_shares_one_where_clause_between_count_and_page():
    """A filter applied to the page but not the count (or the reverse) makes `total`
    disagree with the pages — which is the only number a consumer has to check."""
    body = _route_source()
    uses = body.count("WHERE {where}")
    assert uses >= 2, (
        f"the count query and the page query must share one WHERE clause "
        f"(found {uses} uses of `WHERE {{where}}`)"
    )


def test_route_returns_the_pagination_envelope():
    """The route returned a bare JSON list, so a consumer had no total to page against —
    it could only count what it had already read. Every other paginated route here
    returns `{data, total, limit, offset}`.

    The echoed page size is matched by shape, not by the variable name: whether the route
    returns `limit` or the resolved `page_size` is an implementation choice, but the
    envelope's four keys and its agreement with the size actually applied are the
    contract.
    """
    body = _route_source()
    envelope = re.search(
        r'return \{"data": rows, "total": total, "limit": (\w+), "offset": (\w+)\}', body)
    assert envelope, "the stats route does not return the pagination envelope"
    page_size_var = envelope.group(1)
    assert re.search(
        rf"SELECT COUNT\(\*\) AS n FROM control\.generation_stats WHERE \{{where\}}",
        body), "the stats route does not count the rows it is about to serve"
    # The echoed page size must be the one that reached the query, not a dead parameter.
    assert re.search(rf"params \+ \[{page_size_var}, {envelope.group(2)}\]", body), (
        f"the route echoes {page_size_var} but does not apply it to the page query"
    )


def test_last_n_ticks_still_works_and_no_longer_caps_the_route():
    """`last_n_ticks` is the existing consumer's parameter (the UI dashboard reads it at
    `last_n_ticks=200`, and data-lab's readiness sensor has read it), so it must keep
    answering — as a page size, not as the ceiling on the relation."""
    body = _route_source()
    assert re.search(r"last_n_ticks: Optional\[int\] = Query\(None, le=\d+\)", body), \
        "last_n_ticks is gone, or is no longer optional — an existing reader would 422"
    # It has to feed the page size rather than sit unused. `limit` is the variable in
    # that expression and `page_size` the result, so both must appear in the resolution.
    resolution = re.search(r"page_size = (.*)", body)
    assert resolution, "the route never resolves a page size"
    assert "last_n_ticks" in resolution.group(1), (
        "last_n_ticks does not reach the page size — the parameter is accepted and "
        "then ignored, which looks like it worked"
    )
    assert "limit" in resolution.group(1), (
        "the page size ignores limit, so a caller cannot page the route at all"
    )


def test_ambiguous_limit_and_last_n_ticks_is_rejected_not_guessed():
    """Two page sizes at once must not be resolved silently — FastAPI would otherwise
    pick one and the caller could not tell which, which is how a mirror ends up short.

    Matched whitespace-insensitively: the raise may wrap the status code onto its own
    line, and the point is that a 400 exists, not how it is formatted.
    """
    body = _route_source()
    assert re.search(r"HTTPException\(\s*400", body), (
        "the stats route must reject a request that carries both limit and last_n_ticks "
        "with different values, rather than silently preferring one"
    )


@pytest.mark.usefixtures("ensure_api_reachable")
def test_route_answers_a_window_alone(quiesced_generator):
    """Neither window is required: a consumer asking only for the insert clock must get
    an answer, not a 422 — the failure that kept `/grocery/pos/transactions` a full reload
    until t_6d2ebc52."""
    client = quiesced_generator
    only_clock = client.get("/grocery/stats/generation",
                            params={"limit": 1, "created_after": FAR_PAST,
                                    "created_before": FAR_FUTURE})
    assert only_clock.status_code == 200, (
        f"an insert-clock-only window was rejected: {only_clock.status_code} "
        f"{only_clock.text[:200]}"
    )
    unfiltered = client.get("/grocery/stats/generation", params={"limit": 1}).json()
    assert only_clock.json()["total"] == unfiltered["total"] >= 1, (
        "the wide insert window and no window disagree on the row count"
    )


@pytest.mark.usefixtures("ensure_api_reachable")
def test_empty_window_is_empty_in_total_and_in_data(quiesced_generator):
    """A window that cannot contain anything has to say so in `total` too, or the count
    and the pages disagree and a consumer's completeness check passes on a hole."""
    client = quiesced_generator
    for params in ({"created_after": FAR_FUTURE}, {"start_dt": FAR_FUTURE}):
        body = client.get("/grocery/stats/generation",
                          params=dict(params, limit=1000)).json()
        assert body["total"] == 0, f"{params} matched rows: total={body['total']}"
        assert body["data"] == [], f"{params} returned rows"


@pytest.mark.usefixtures("ensure_api_reachable")
def test_last_n_ticks_is_honoured_and_offset_pages_through_it(quiesced_generator):
    """The old parameter must still mean "the newest N", and paging has to be able to
    walk past that N — which is the whole point of the change."""
    client = quiesced_generator
    body = client.get("/grocery/stats/generation",
                      params={"last_n_ticks": 5}).json()
    assert body["limit"] == 5, f"last_n_ticks was ignored: limit={body['limit']}"
    assert len(body["data"]) <= 5

    newest = [row["stat_id"] for row in body["data"]]
    if len(newest) < 2:
        pytest.skip("fewer than two ledger rows to page through")
    older = client.get("/grocery/stats/generation",
                       params={"limit": 5, "offset": len(newest)}).json()["data"]
    page_ids = {row["stat_id"] for row in older}
    assert not (page_ids & set(newest)), (
        f"offset={len(newest)} re-returned rows from the first page: a page boundary "
        "inside a tie cluster duplicates and drops rows"
    )


# ---------------------------------------------------------------------------
# Ask 2 — the backfill writes the ledger, stamped with the scenario it ran
# ---------------------------------------------------------------------------

def test_backfill_records_a_ledger_row():
    """The defect: `run_backfill` never called `record_stats`, so every day written by a
    backfill — the 30-day window of a fresh install, and every day a gap-fill repairs —
    left no telemetry. A consumer asking whether the generator was up during a dip found
    the answer only for realtime ticks."""
    backfill = _backfill_source()
    assert "generation_stats" in GENERATOR_MAIN.read_text() and \
        "record_stats(" in backfill, (
        "run_backfill writes no control.generation_stats row: a backfilled day is "
        "invisible in the tick ledger, which is how 30 days of transactions came to "
        "exist with no telemetry explaining them (t_ac80c514)"
    )
    # The hourly loop is where the tick's own counts and scenario are known.
    hour_loop = backfill[backfill.index("for hour in range("):]
    assert "record_stats(" in hour_loop, (
        "the backfill writes no ledger row per simulated hour; a per-day aggregate would "
        "lose the hourly resolution the realtime path records every tick"
    )


def test_backfill_stamps_the_scenario_the_hour_ran_under():
    """The tag on the ledger row has to be the one the hour's transactions were written
    with — `scenario.scenario_tag`, the same object the hour's `generate_pos_transactions`
    received. A tag recomputed at write time could disagree with the rows it describes,
    which is the failure the card reports: a holiday regime in the fact tables and
    nothing in the ledger.

    Scoped to the INSERT itself: `scenario.scenario_tag` also appears on the hour's
    `inventory.flush_sales` call, so searching the whole loop would pass on the ledger
    row being untagged.
    """
    call = _backfill_record_stats_call()
    assert "scenario.scenario_tag" in call, (
        "the backfilled ledger row must be stamped with the hour's own "
        "`scenario.scenario_tag` — the context its transactions were generated under"
    )


def test_backfill_records_the_counts_it_actually_wrote():
    """The ledger exists to answer "did the generator run, and how much did it make?".
    Recording the *planned* volume instead of the rows written would make a tick that
    wrote nothing look like a busy one — and a stockout-capped tick (t_959cd040) writes
    strictly fewer rows than it planned."""
    call = _backfill_record_stats_call()
    assert "len(depletion)" in call, (
        "the backfilled ledger row must record the POS rows actually written "
        "(len(depletion)), not the planned `pos_count`"
    )
    assert not re.search(r"\bpos_count\b", call), (
        "the backfilled ledger row records the planned pos_count rather than the rows "
        "written; a stockout-capped or fully-sold-out hour would read as a busy tick"
    )
    assert "len(online_depletion)" in call, (
        "the backfilled ledger row must record the online rows actually written; the "
        "realtime path records `orders_generated`, so a backfilled hour would read as "
        "if the online channel had produced nothing"
    )


def test_backfill_ledger_row_is_written_in_the_hours_transaction():
    """A ledger row is evidence about the tick, so it must be written inside the hour's
    own loop — after that hour's rows, and before the day commits. Written after the
    hourly loop a crash would leave the day's data on disk with no ledger; written in a
    later day's batch, the ledger would describe ticks whose rows had rolled back."""
    backfill = _backfill_source()
    call_at = backfill.index("record_stats(")
    hour_loop_start = backfill.index("for hour in range(")
    day_end = backfill.index("\n        if not is_partial:")
    assert hour_loop_start < call_at < day_end, (
        "the ledger row is not written inside the hourly loop: a day's rows could commit "
        "and the ledger row not, leaving telemetry for data that was rolled back"
    )


def test_backfill_does_not_bump_the_state_clock():
    """`last_tick_at` is what `/status` and data-lab's readiness sensor read as "the
    generator is alive". During a backfill the generator is simulating the past, so
    stamping the wall clock there would make a backfilled hour look like live progress
    and `last_tick_at` would stop being comparable with the ledger's own `recorded_at`.
    """
    call = _backfill_record_stats_call()
    assert "bump_state_clock=False" in call, (
        "run_backfill must pass bump_state_clock=False: stamping last_tick_at while "
        "backfilling history makes the readiness sensor read a generator that is "
        "simulating yesterday as one that is alive (t_ac80c514)"
    )


def test_record_stats_is_reachable_from_both_generation_paths():
    """The docstring at the top of the generator lists `record_stats()` as a lifecycle
    phase of `run_tick`. The backfill is the other path that produces rows a consumer
    will later ask about, so it has to reach the same writer rather than open-coding a
    second INSERT that can drift from the first (as gas-station and support's inline
    INSERTs can)."""
    source = GENERATOR_MAIN.read_text()
    assert source.count("def record_stats") == 1, "more than one record_stats writer"
    start = source.index("def run_backfill")
    backfill = source[start:source.index("\ndef ", start + 10)]
    assert "record_stats(" in backfill, (
        "run_backfill writes its own INSERT instead of calling record_stats: the two "
        "writers will drift, and record_stats also bumps the state clock that the "
        "readiness sensor reads"
    )


# ---------------------------------------------------------------------------
# Ask 3 — the scenario relations are manual-only; say so in the route's own docs
# ---------------------------------------------------------------------------

def test_scenario_relations_have_no_seeder():
    """`control.active_scenarios` and `control.scenario_schedules` are written only by
    the POST routes. Nothing seeds them, so they are 0 rows on every slot until someone
    calls them by hand — the calendar regimes (labour day, thanksgiving, …) come from
    `scenario_engine._get_holiday_multiplier`, a pure function of the date that touches
    neither table. `idx_scenario_schedules_dates` exists for the read in
    `get_active_scenario_names`, not as evidence of seeding.

    This test pins the *answer* to the card's question so a future "the schedules table
    is empty, let me add a seeder" is a deliberate change rather than a silent one.
    """
    for path in (REPO_ROOT / "grocery" / "generator" / "main.py",
                 REPO_ROOT / "grocery" / "generator" / "scenarios" / "scenario_engine.py"):
        assert not re.search(r"INSERT INTO control\.(active_scenarios|scenario_schedules)",
                             path.read_text()), (
            f"{path.name} now seeds control.active_scenarios / scenario_schedules; "
            "update the API route docs, which state they are manual-only"
        )

    # The only writers left must be the two POST route pairs (one per industry), and each
    # writes its own relation once.
    api = (REPO_ROOT / "base" / "api" / "main.py").read_text()
    writers = re.findall(
        r"INSERT INTO control\.(active_scenarios|scenario_schedules)\b", api)
    assert sorted(writers) == ["active_scenarios", "active_scenarios",
                               "scenario_schedules", "scenario_schedules"], (
        f"unexpected writers of the scenario relations in base/api/main.py: {writers}"
    )
